// ==========================================
// Project Monolith: Source Probe Demo
// Protocol 80 MVP Phase - Test Document
// ==========================================
//
// This document demonstrates all probe types and their usage patterns.
// After compilation, the embedded probe data can be extracted via query.

#import "std_probe.typ": *

// ============================================================================
// Document Setup
// ============================================================================

#set page(
  paper: "a4",
  margin: (x: 2.5cm, y: 2.5cm),
)

#set text(
  font: "New Computer Modern",
  size: 11pt,
)

#set heading(numbering: "1.1")

// ============================================================================
// Title Section with Structure Probes
// ============================================================================

#probe_struct("title", kind: "title", level: 0, edge: "start", title: "Source Probe System Demo")

#align(center)[
  #text(size: 24pt, weight: "bold")[Source Probe System Demo]
  
  #v(0.5em)
  
  #text(size: 12pt, fill: gray)[
    Protocol 80 MVP Phase - Project Monolith
  ]
  
  #v(1em)
]

#probe_struct("title", kind: "title", level: 0, edge: "end")

// ============================================================================
// Abstract with Semantic Probe
// ============================================================================

#probe_block("abstract", kind: "abstract", level: 1, title: "Abstract")[
  #probe_semantic("abstract-meta", (
    type: "ai-summary",
    language: "en",
    word_count: 50,
    auto_generated: false,
  ))
  
  This document demonstrates the Source Probe system implemented for Project Monolith.
  Source Probes are invisible metadata markers that enable AI agents to query the 
  physical layout of compiled Typst documents without affecting visual rendering.
]

#v(1em)

// ============================================================================
// Section 1: Geo Probes
// ============================================================================

#probe_heading("sec-geo", 1)[Geo Probes: Physical Coordinate Markers]

#probe_block("sec-geo-content", kind: "section", level: 1)[
  Geo probes mark specific physical positions in the document. They are useful for:
  
  #probe_geo_pair("geo-list")[
    - *Multimodal RAG*: Crop specific regions from PDF screenshots
    - *Click-to-source mapping*: Navigate from preview to source code
    - *Visual annotations*: Highlight specific text regions
  ]
  
  #v(0.5em)
  
  Here's an example of inline geo probes marking important text:
  
  The formula#probe_geo("formula-start", anchor: "start")
  $ E = m c^2 $#probe_geo("formula-end", anchor: "end")
  is perhaps the most famous equation in physics.
]

// ============================================================================
// Section 2: Struct Probes
// ============================================================================

#probe_heading("sec-struct", 1)[Struct Probes: Logical Structure Markers]

#probe_block("sec-struct-content", kind: "section", level: 1)[
  Struct probes mark logical document structure boundaries. They enable:
  
  - *Outline generation*: Build interactive document navigation
  - *Section-level AI operations*: Summarize or translate sections
  - *Cross-page tracking*: Follow content that spans multiple pages
  
  #v(0.5em)
  
  === Subsection Example
  
  #probe_struct("subsec-example", kind: "subsection", level: 2, edge: "start", title: "Subsection Example")
  
  This is a subsection that demonstrates nested structure probes.
  The structure tree will show this as a child of Section 2.
  
  #probe_struct("subsec-example", kind: "subsection", level: 2, edge: "end")
]

// ============================================================================
// Section 3: Semantic Probes
// ============================================================================

#probe_heading("sec-semantic", 1)[Semantic Probes: AI Metadata Injection]

#probe_block("sec-semantic-content", kind: "section", level: 1)[
  Semantic probes embed invisible AI-related metadata for:
  
  - *Audit trails*: Track AI-generated content
  - *Quality metrics*: Store confidence scores
  - *Version control*: Link to prompt IDs and model versions
  
  #v(0.5em)
  
  #probe_ai_content(
    "ai-para-001",
    "claude-3.5-sonnet",
    "explain-technical",
    confidence: 0.95,
    meta: (
      temperature: 0.7,
      max_tokens: 500,
    )
  )[
    This paragraph was hypothetically generated by an AI model.
    The semantic probe attached to it contains metadata about
    which model was used, the prompt ID, and a confidence score.
    This information is completely invisible in the rendered PDF
    but can be extracted via the probe query system.
  ]
]

// ============================================================================
// Section 4: Figure Tracking
// ============================================================================

#probe_heading("sec-figures", 1)[Figure Tracking]

#probe_block("sec-figures-content", kind: "section", level: 1)[
  Figures can be tracked with specialized probes:
  
  #probe_figure("fig-demo", fig_kind: "image", caption: "Demo Figure")[
    #figure(
      rect(width: 80%, height: 5cm, fill: gradient.linear(blue, purple)),
      caption: [A demonstration figure with gradient fill],
    )
  ]
  
  The probe captures the figure's location, enabling AI agents to:
  - Answer questions about specific figures
  - Crop figure regions for multimodal analysis
  - Cross-reference figures with text mentions
]

// ============================================================================
// Section 5: Math and Code Tracking
// ============================================================================

#probe_heading("sec-math-code", 1)[Math and Code Tracking]

#probe_block("sec-math-code-content", kind: "section", level: 1)[
  
  === Mathematical Expressions
  
  #probe_math("quadratic", display: true)[
    $ x = (-b plus.minus sqrt(b^2 - 4 a c)) / (2 a) $
  ]
  
  The quadratic formula above is tracked as a display math probe.
  
  #v(0.5em)
  
  === Code Blocks
  
  #probe_code("rust-example", lang: "rust")[
    ```rust
    fn main() {
        println!("Hello, Project Monolith!");
    }
    ```
  ]
  
  Code blocks are wrapped with struct probes that include the language metadata.
]

// ============================================================================
// Section 6: Bounding Boxes
// ============================================================================

#probe_heading("sec-bbox", 1)[Bounding Box Calculation]

#probe_block("sec-bbox-content", kind: "section", level: 1)[
  When probes are emitted as start/end pairs, the IntrospectionService
  can calculate bounding boxes automatically.
  
  #probe_geo_pair("highlighted-paragraph")[
    This entire paragraph is wrapped in a geo probe pair.
    The system will calculate the vertical extent from the
    start probe at the top to the end probe at the bottom.
    This enables precise region highlighting and cropping.
  ]
  
  The bounding box data includes:
  - Start position (page, x, y)
  - End position (page, x, y)  
  - Calculated height
]

// ============================================================================
// Conclusion
// ============================================================================

#probe_heading("sec-conclusion", 1)[Conclusion]

#probe_block("sec-conclusion-content", kind: "section", level: 1)[
  The Source Probe system provides three types of markers:
  
  + *Geo Probes*: Physical coordinate markers for RAG and visual mapping
  + *Struct Probes*: Logical structure boundaries for navigation
  + *Semantic Probes*: AI metadata injection for audit trails
  
  Together, these enable AI agents to understand not just the text content
  of documents, but their precise physical layout in the rendered PDF.
]

// ============================================================================
// Emit Probe Data
// ============================================================================

// This MUST be called at the end of the document
// It embeds all probe data as queryable metadata
#emit_probes_json()

